.
./andrew
./ant
./apps
./archive
./build-ctsrv-Desktop_Qt_5_6_0_MSVC2015_32bit-Debug
./build-ctsrv-Desktop_Qt_5_7_0_clang_64bit-Debug
./build-ctsrv-Desktop_Qt_5_7_0_clang_64bit-Release
./build-ctsrv-iphoneos_clang_Qt_5_7_0_for_iOS-Debug
./build-ctsrv-iphoneos_clang_Qt_5_7_0_for_iOS-Release
./build-radio-Desktop_Qt_5_6_0_GCC_64bit-Debug
./build-radio-Desktop_Qt_5_6_0_MSVC2015_32bit-Debug
./build-radio_qml-Desktop_Qt_5_6_0_GCC_64bit-Debug
./build-radio_qml-Desktop_Qt_5_9_1_GCC_64bit-Debug
./build-rmg-Desktop_Qt_5_6_0_MSVC2015_32bit-Debug
./build-rmg-Desktop_Qt_5_7_0_clang_64bit-Debug
./build-rmg-Desktop_Qt_5_7_0_clang_64bit-Release
./build-rmg-iphoneos_clang_Qt_5_7_0_for_iOS-Release
./common
./computrainer
./ctsrv
./ctt
./deploy
./Desktop_Qt_5_6_1_GCC_64bit-Debug
./Desktop_Qt_5_7_0_clang_64bit-Debug
./fake_ss
./glib
./hbsim
./hbsim_qml
./hbsim_save
./lusb
./__MACOSX
./mslibs
./ogl1
./ogl2
./painteditem
./racermate
./radio
./radio_qml
./rmate
./rmg
./serial_scanner
./templates
./tlib
./tmp
./Wireframe
